### ISSUE TITLE
Trail Colours Not Saving

### ISSUE THREAD

**Issue by Caitlynmcc234** [TheBearodactyl/gay-wave-trail#9]
i changed the colours of the wave trail, and it does use them for a bit, but it ends up removing it, i think when i close the game and re open it.
![image](https://github.com/user-attachments/assets/be8b6c09-058e-466c-bfde-f1c20f7159ce)

**Comment by Caitlynmcc234** [comment]
![image](https://github.com/user-attachments/assets/532f1795-b872-4555-a3f1-685cb9975348)
this is what happens when i close and re open the game

**Comment by TheBearodactyl** [comment]
will fix now, sorry about that

**Comment by Caitlynmcc234** [comment]
Did you fix it yet?

**Comment by TheBearodactyl** [comment]
not just yet, got distracted lol
sorry about that
it'll be fixed along with a new feature in the next update :3

**Comment by Caitlynmcc234** [comment]
Hello

**Comment by TheBearodactyl** [comment]
> Hello

still working on it, i dumb

**Comment by TheBearodactyl** [comment]
fixed in the next update, will be pushing later tonight

**Comment by Caitlynmcc234** [comment]
It's still not saving it for me and resets all of them to #FFFFFF, and also, the trail colour is black whenever i enable the gaydient instead of what it is supposed to be

**Comment by TheBearodactyl** [comment]
next update isn't out yet, again i am so sorry, it's going a full rewrite right now so it's gonna be worth the wait :(

**Comment by Caitlynmcc234** [comment]
ooh ok there was an update on geode and i thought that was it.

**Comment by TheBearodactyl** [comment]
no that was from a while ago and only just now got accepted
i'll tell you what though, i'll upload a temp release using the current code with the new setting for now and you can probably install and use it until the complete rewrite is complete

**Comment by TheBearodactyl** [comment]
if you want to see the code for the rewrite check out the [rewrite](https://github.com/TheBearodactyl/gay-wave-trail/tree/rewrite/src/settings) branch

**Comment by TheBearodactyl** [comment]
@Caitlynmcc234 rewrite has been merged and will soon be released :3

**Comment by TheBearodactyl** [comment]
@Caitlynmcc234 just waiting for the update to be accepted on the index, the bug has been completely fixed and the setting itself has had a few additions

**Comment by TheBearodactyl** [comment]
UPDATED
